### ISSUE TITLE
Failed to find any matching files for reinforced_cvae/01-09_11-12-05/breakpoints/best_test_bleu.ckpt

### ISSUE THREAD

**Issue by ha-lins** [Claude-Zhou/MojiTalk#1]
Hi ! Thanks for your code!

When i run Reinforced CVAE model , i modified line 63/74 of rl_run.py as 
"cvae/01-08_07-16-13/breakpoints/at_step_20500.ckpt" and "classifier/01-07_13-08-49/breakpoints/best_test_loss.ckpt" .But it didn't save the best_test_bleu.ckpt 
and i got the error information:

> INFO:tensorflow:Restoring parameters from reinforced_cvae/01-09_11-12-05/breakpoints/best_test_bleu.ckpt
2019-01-10 08:37:14.839739: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for reinforced_cvae/01-09_11-12-05/breakpoints/best_test_bleu.ckpt
2019-01-10 08:37:14.839756: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for reinforced_cvae/01-09_11-12-05/breakpoints/best_test_bleu.ckpt

Traceback (most recent call last):
  File "/data/linshuai/anaconda3/envs/tf12py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/data/linshuai/anaconda3/envs/tf12py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/data/linshuai/anaconda3/envs/tf12py35/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/data/linshuai/anaconda3/envs/tf12py35/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for reinforced_cvae/01-09_11-12-05/breakpoints/best_test_bleu.ckpt
         [[Node: save/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_9/tensor_names, save/RestoreV2_9/shape_and_slices)]]
         [[Node: save/RestoreV2_9/_115 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_176_save/RestoreV2_9", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

The log.txt saved the result until **epoch:6 step:27560** ,yet **the checkpoint/ is empty** .
what's the reason of the problem?Could you please tell me ?Thanks a lot!

**Comment by claude-zhou** [comment]
Seems the file name in line 157 is not in line with the one in line 163. 
Maybe replace the “best_test_bleu.ckpt” in line 163 with something saved in line 157. 
Let me know if this works. 
Thank you

**Comment by claude-zhou** [comment]
It’s empty probably because the program never enter the if-clause in line 156. You may want to find out why. And you can just remove those conditions of saving breakpoints.

**Comment by ha-lins** [comment]
After modifying line 163 and 156 ,it can run well now.Thanks a lot.
Now i still have some questions as follows:
How can we modify the specified emoji label for response?  Or what the rule for specifying the label is ?

**Comment by ha-lins** [comment]
Hi ,for the former question, i guess we can only change the first character in the test.ori  manually to modify the emoji label?Besides,i got another problem,which is some out sentences are too long and meanless in the .out file,e.g.
`
50 i don 't have one .
51 idk what he said tho but he 's gunna be good tho
 52 documents zverev pv ju sono patriots takpe broccoli buffoon internet jack takpe broccoli takpe jetzt broccoli human takpe bd dumpster takpe broccoli glenn enough       tomi broccoli takpe internet broccoli takpe glenn broccoli takpe human jetzt dumpster takpe broccoli enough glenn takpe broccoli glenn human jetzt takpe dumpste      r jack broccoli
 53 hope you 're ok , don 't worry wade obamacare tidur obamacare subject warrior nada potus suits camo mejor camo potus nfc hamster posed camo p thanx atp hamster t      raffic brats biggie knickers hunk potus camo hamster posed traffic patrick knickers hamster brats traffic biggie hunk dare knickers hamster
` 
Could you tell me the reason of this problem?Appreciate for your help~
