### ISSUE TITLE
Twitter Conversations dataset

### ISSUE THREAD

**Issue by sunjid-rahman** [Claude-Zhou/MojiTalk#4]
Need code of collecting large corpus of twitter conversations. I want to collect datasets of different language then will apply it in code to check accuracy..

**Comment by claude-zhou** [comment]
Twitter API has significantly changed since the data was collected in Aug, 2017. (https://developer.twitter.com/en/docs/changelog/standard-premium)
I don't think my previous crawler would work any more.
